### ISSUE TITLE
`stream.next()` blocks when camera unplugged

### ISSUE THREAD

**Issue by EtomicBomb** [raymanfx/libv4l-rs#16]
When I start a stream and unplug the camera, the `stream.next()` call blocks forever. It would be nice if I could set a timeout. Perhaps I'm missing something, but I can't see a way to do that in this library. 
It seems like there's a [poll function](https://www.kernel.org/doc/html/v5.4/media/uapi/v4l/func-poll.html#func-poll) that's made for this.
Perhaps this should be the standard behavior - I think most users would expect an error when a camera is unplugged.

**Comment by raymanfx** [comment]
I'm going to test this later. Returning an error (or None in the case of `next()` should definitely be the default behavior.

**Comment by raymanfx** [comment]
Okay, I was able to reproduce this.
Do you want to work on a PR that adds something like a `set_timeout(..)` and a `poll(..)` method to the two stream implementations in `src/io/{mmap, userptr}/stream.rs`?

The `next()` method should then perform the polling and return `None` in case of timeout I think. I'm going to merge the `next` branch into master today or tomorrow, so I'd advise to start on top of that branch instead of the current master.
