### ISSUE TITLE
Device enumeration bug

### ISSUE THREAD

**Issue by filiphazardous** [raymanfx/libv4l-rs#31]
I ran into a bug with device enumeration. The following script misplaces part of the index:  
```
fn main() {  
    let device_list = v4l::context::enum_devices();  
    for device in device_list.iter() {  
        let index = device.index();  
        let path = device.path();  
        println!("Device index: {} and path {}", index, path.display());  
    }  
}
```  

Produces the following output:
```
Device index: 3 and path /dev/video3  
Device index: 2 and path /dev/video2  
Device index: 1 and path /dev/video1  
Device index: 0 and path /dev/video0  
Device index: 11 and path /dev/video11  
Device index: 1 and path /dev/video10
```  

As you see, the last line drops a zero.  

Cards 10 and 11 are v4l2-loopbacks created with the following line:  
`v4l2loopback devices=2 card_label="VirtualCam1,VirtualCam2" exclusive_caps=1,0 video_nr=10,11`
Edit: Trying to fix missing line-breaks

**Comment by raymanfx** [comment]
I guess that's because of this reverse character parsing here: https://github.com/raymanfx/libv4l-rs/blob/master/src/context.rs#L79, where it will parse the string "01" as number and thus end up with `1`.

Honestly I don't remember why I opted for reverse char splitting here. Looks like that portion of code should be revisited. I'll see whether I get some time to look into this tomorrow.

**Comment by raymanfx** [comment]
Issue can be reproduced here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c12d5de22c082408c723c889fac0d70c.
